### ISSUE TITLE
No way to get deleted items?

### ISSUE THREAD

**Issue by brynnb** [Doist/todoist-api#13]
There is the is_deleted property of an item, but if an item is deleted it is not pulled in with the API when you get items. I feel like I am maybe missing something because I don't know why this property would exist if it would never be anything other than 0. 

The API docs say one cannot rely on webhooks for determining things like this otherwise I would use that. As it stands now, I just have to re-sync constantly and assume that if an item stops syncing in and isn't in the completed items, it's been deleted. And hope that the user doesn't complete more than 50 items between my syncing because then it will show as deleted in my app when it's not.

**Comment by eleftherios-c** [comment]
You can see an item having the property `is_deleted` set to `1`, when you do a partial sync (by using your last known `seq_no`), and the item has been deleted between the last time you synced and the present.  So that partial sync reply includes the deleted item, and you can observe that it has been deleted by looking into the `is_deleted` property sent by the server.

If you only do full syncs, then you will never see an object with `is_deleted` have a value other than `0`, because as you noticed the objects with `1` are never returned on a full sync.  So it could be said that `is_deleted` actually works more like a flag to mark an item for deletion, not as a real property.

So as deleted objects are marked deleted, and then after some short time automatically removed from the DB, it's not actually possible to get deleted items since they don't exist anymore.

**Comment by brynnb** [comment]
@eleftherios-c Thanks a bunch for the response. It's been a couple months since I looked at this but your description seems to make sense. Perhaps I didn't realize the differences between full and partial syncs, or maybe the documentation didn't make this particular aspect clear. I appreciate your detailed support.
