### ISSUE TITLE
Add sample code for using OAuth with Python

### ISSUE THREAD

**Issue by alexandrosio** [Doist/todoist-api#29]
Hello Doist team,

Could you please provide us with some sample code on how to use OAuth with Python?; the python tab under OAuth, on your API's documentation page, is empty.

Best,
Alexandros Nicolaides

**Comment by PotHix** [comment]
Hi @alexandrosio,

The reason for the lack of Python code samples on the OAuth workflow section is because it's not implemented in our Python library yet. 

We have plans to do that in the near future and we'll add the code samples that as soon as it gets implemented.

Thanks for pointing that out anyway! :D
