### ISSUE TITLE
Add Access-Control-Allow-Origin into server response

### ISSUE THREAD

**Issue by Cosmitar** [Doist/todoist-api#30]
Hi, I'm developing a [javascript API client](https://github.com/Cosmitar/todoist-js) and making some oAuth2 tests found that can't read `https://todoist.com/oauth/access_token` response since browser is not getting authorization from server. Therefore, can't exchange an access token.
Error log is
```
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:8080' is therefore not allowed access.
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
I think that a good option is to add the `App Service URL` (from App Console) as value for `Access-Control-Allow-Origin` into server response.

What do you think?

**Comment by rincedd** [comment]
As far as I understand, the correct way to support serverless JS web applications would be to allow the [OAuth Implicit Grant](https://tools.ietf.org/html/rfc6749#section-4.2) flow that does not require exposing the client secret in the browser. Are there any plans on this?

**Comment by Cosmitar** [comment]
You're right @rincedd, with current [__token exchange__](https://developer.todoist.com/#oauth) process you're forced to send _client_secret_ in order to get an _access token_

**Comment by lefcha** [comment]
Unfortunately OAuth2 doesn't provide a secure solution for this problem; you need to store the `client_secret` on the server-side, and not on the client.

We also don't plan on implementing the Implicit Grant flow, as it's event less secure, because only knowing the `client_id` is enough to grant you an access token.

We can only suggest that if you're using the OAuth2 authentication, you implement a server-side that does the `client_secret` and `code` exchange with our server to get the `access_token`, and you never expose the `client_secret` on the client.

Otherwise a better solution would be to use our `/API/v7/user/login` call, which accepts a `username` and `password` parameter, and returns the user data, including the user's API token.

**Comment by Cosmitar** [comment]
I understand the OAuth2 client-side security concerns, I think that a server workaround is the solution here.
The option of `/API/v7/user/login` seems worse in security concept, due to a 3rd party asking a user/pass combination is not appropriate, don't you think? Actually, OAuth tries to solve that problem offering the user to authenticate against the trusted server and authorise a 3rd party to interact with certain data. 

Thanks for your reply @lefcha, I'll finish the [JS Client](https://github.com/Cosmitar/todoist-js) with this approach in mind.

**Comment by PotHix** [comment]
Looks like the answers provided helped to figure out a solution. I'm closing this one but please reopen in case you still need information. :)
