### ISSUE TITLE
No way for client (non premium) to know whether a task has been completed or not (v7)

### ISSUE THREAD

**Issue by khurshid-alam** [Doist/todoist-api#35]
This is related to #20 

As of now there is no way for non premium client users to know whether a task has been completed or not on server side with v7 api.

1. The method `get-all-completed-items` is premium method

2. The other method `api.activity.get()` is also for premium users only.

3 The traditional sync method (`api.sync or api.items.sync()`) doesn't return completed task either.

So this is problematic for two way sync with a application.  During first sync it is impossible for a client to get previously completed-tasks.

During incremental sync it is also impossible . As api.sync() doesn't bring completed tasks , it simply vanishes for client. There are two possibilities a) completed, b) deleted. But client doesn't know that unless it again checks with `api.items.get_by_id ` which in turn makes api.sync() concept useless as it is supposed to be incremental sync.

Making one of first two method available for non-premium users will help preventing excessive requests and thus abusing the service.

**Comment by PotHix** [comment]
Hi @khurshid-alam,

The two methods mentioned are premium only, we have no plans to change it, hope you understand.

We can still look for an alternative. :)

You may solve your problem by using partial syncs. Here is an example of how it would work using our Python lib:

Using partial sync command

```
$ python -c "import todoist, os, pprint; token = os.environ['token']; api = todoist.TodoistAPI(token); pprint.pprint(api.sync())" 
{'collaborator_states': [],
 'collaborators': [],
 'day_orders': {},
 'day_orders_timestamp': '1501710760.02',
 'filters': [],
 'full_sync': False,
 'items': [],
 'labels': [],
 'live_notifications': [],
 'live_notifications_last_read_id': 0000000000,
 'notes': [],
 'project_notes': [],
 'projects': [],
 'reminders': [],
 'sync_token': 'xxxxxxxxxx',
 'temp_id_mapping': {}}
```

The sync token (xxxxxxxx in this example) is being stored in the cache. In this case we have nothing to sync. Let's use grep to look for `checked` tasks:

```
$ python -c "import todoist, os, pprint; token = os.environ['token']; api = todoist.TodoistAPI(token); pprint.pprint(api.sync())" | egrep checked

```

It's empty. :)

Then let's complete one of our tasks and run the command again:

```
$ python -c "import todoist, os, pprint; token = os.environ['token']; api = todoist.TodoistAPI(token); pprint.pprint(api.sync())" | egrep checked
            'checked': 1,
```

Here is our completed task on partial sync. In case you run it again, it will be empty because the `sync` command is reusing the `sync_token` in cache:

```
$ python -c "import todoist, os, pprint; token = os.environ['token']; api = todoist.TodoistAPI(token); pprint.pprint(api.sync())" | egrep checked

```

In case I decide to uncheck the task it will get back to the list:

```
$ python -c "import todoist, os, pprint; token = os.environ['token']; api = todoist.TodoistAPI(token); pprint.pprint(api.sync())" | egrep checked
            'checked': 0,
```

You can try it by yourself in case you have our Python library installed.

Please let us know if this helps or we can try to think about a different solution.

**Comment by khurshid-alam** [comment]
Well, that's unfortunate. But it should work with workaround you suggested. Thanks.
