### ISSUE TITLE
duplicate tasks

### ISSUE THREAD

**Issue by kandros** [Doist/todoist-api#36]
What is the recommended way to duplicate tasks with deeply nested subtasks using the APIs?

I tried to inspect what happens when duplicating a task from the app intercepting the event with a webhook, but it's far from clear what's going on

**Comment by PotHix** [comment]
Hi @kandros,

We're currently using [item_add](https://developer.todoist.com/sync/v7/#add-an-item) with all tasks and sub-tasks in order to duplicate it.

> I tried to inspect what happens when duplicating a task from the app intercepting the event with a webhook, but it's far from clear what's going on

After clicking on "duplicate" you will notice a `sync` call on your network inspection and on "headers" you will see the `commands` parameter with an `item_add` command and many tasks being sent.

Hope it helps.
